I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script
    python:
  File "game/script.rpy", line 20, in <module>
    inventory,add_item("log", quantity=99)
NameError: name 'add_item' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script
    python:
  File "C:\Users\Sanzid\Desktop\Renpy\renpy-8.1.0-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Sanzid\Desktop\Renpy\renpy-8.1.0-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 20, in <module>
    inventory,add_item("log", quantity=99)
NameError: name 'add_item' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
Advanced renpy inventory 1.0
Thu Aug 24 00:16:51 2023
